# cluster.yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: roboshop-ng
  region: us-east-1

managedNodeGroups:
  - name: roboshop-ng
    instanceTypes: ["m5.large"]   # start on on-demand; add Spot later
    desiredCapacity: 2
    minSize: 1
    maxSize: 4
